# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36e5544d1a75527839913a5368b0c1fa6df1cc072e2e73252ae0d85025d288f22c3a7b13da7a2522459bc14877704206b3e0675257e36314cd7878af4cb61b8d

test:
  secret_key_base: a47eb28bf473128dfcaef7e4f17274e003dbbc90edafbd02e2d9d23133b67885aeb56a687791750627ca4ef9fc850d71a50a7a8c3ac40a355a57859f0760851f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
